apiVersion: apps/v1
kind: Deployment
metadata:
  name: mattermost-mattermost-team-edition
spec:
  replicas: 1
  strategy:
    type: Recreate
    rollingUpdate: null
  revisionHistoryLimit: 1
  template:
    spec:
      containers:
      - name: mattermost-team-edition
        image: "mattermost/mattermost-team-edition:release-5.27"
        imagePullPolicy: IfNotPresent
        env:
        - name: MM_CONFIG
          valueFrom:
            secretKeyRef:
              name: mattermost-mattermost-team-edition-config
              # ex. mysql://password@protocol(host:port)/database-name?charset=utf8mb&parameter2=...
              key: db-url
        ports:
        - name: http
          containerPort: 8065
          protocol: TCP
        livenessProbe:
          initialDelaySeconds: 90
          timeoutSeconds: 5
          periodSeconds: 15
          httpGet:
            path: /api/v4/system/ping
            port: http
        readinessProbe:
          initialDelaySeconds: 15
          timeoutSeconds: 5
          periodSeconds: 15
          httpGet:
            path: /api/v4/system/ping
            port: http
        volumeMounts:
        - mountPath: /mattermost/data
          name: mattermost-data
        - mountPath: /mattermost/plugins
          name: mattermost-plugins
        resources: {}
      volumes:
      - name: mattermost-data
        persistentVolumeClaim:
          claimName: mattermost-mattermost-team-edition
      - name: mattermost-plugins
        persistentVolumeClaim:
          claimName: mattermost-mattermost-team-edition-plugins
